### ISSUE TITLE
Create Selinium application flowcharts using mermaid.live

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#11]

**Comment by Volatar** [comment]
Assigned to @CalebLuce

**Comment by CalebLuce** [comment]
Through research I have installed Mermaid Preview onto VSCode, understand the basic language of mermaid.live and can surely say that I will be able to make a class diagram. As a dependency, I will need to observe the code created by the coding team once it has been mostly completed, and will have to draft and create the entire diagram from scratch. As far as issues go currently, I cannot quite yet test and learn or be certain of how mermaid works with GitHub as a recognized language. To be able to do so, I will have to attempt posting the class diagram and observing manually how it is read by GitHub. If we have individuals who have learned Markdown and can explain how it is understood by GitHub, I will have a better time understanding the link for mermaid to GitHub. As things currently stand, I have a solid standing point on where to progress as we continue.

**Comment by Volatar** [comment]
Well lets test it shall we.

This is the sample digram when loading mermaid.live, and then copied here by using the copy markdown button.

[![](https://mermaid.ink/img/pako:eNpVkM1qw0AMhF9F6NRC_AI-FBq7zSWlhebmzUF45eyS7A_ymhBsv3vXNoVWJzHzjRAzYhs0Y4ndLdxbQ5LgVCsPeV6byojtk6P-DEXxMh04gQueHxPsnw4BehNitP7yvPH7BYJqPC4YQzLWX-fNqtb8p-cJ6uZIMYV4_uuc7mGCt8Z-mXz-v2OEc-q96ajsqGhJoCJZEdyhY3FkdX5_XBSFybBjhWVeNclVofJz5mhI4fvhWyyTDLzDIWpKXFu6CLlfkbVNQT62OtZW5h_iO1v9?type=png)](https://mermaid.live/edit#pako:eNpVkM1qw0AMhF9F6NRC_AI-FBq7zSWlhebmzUF45eyS7A_ymhBsv3vXNoVWJzHzjRAzYhs0Y4ndLdxbQ5LgVCsPeV6byojtk6P-DEXxMh04gQueHxPsnw4BehNitP7yvPH7BYJqPC4YQzLWX-fNqtb8p-cJ6uZIMYV4_uuc7mGCt8Z-mXz-v2OEc-q96ajsqGhJoCJZEdyhY3FkdX5_XBSFybBjhWVeNclVofJz5mhI4fvhWyyTDLzDIWpKXFu6CLlfkbVNQT62OtZW5h_iO1v9)

**Comment by Volatar** [comment]
@CalebLuce What I need from you is an abstract, general, not-about-our-code diagram or set of diagrams of the Document Object Model to go along with Robert's text about that subject.

**Comment by Volatar** [comment]
I was hoping for a diagram of our web app code but this is on hold for now.
