### ISSUE TITLE
DOM diagram for documentation

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#26]

**Comment by Volatar** [comment]
Completed in 331d195cc088fc6b89c7baca22297119dcbd612f

**Comment by Volatar** [comment]
@Rangodung assigned to review

**Comment by Rangodung** [comment]
Upon checking the diagram, I see that it is flawless. it explains well how the DOM should work. even ask for a second opinion from a professional and even said that its good.
