### ISSUE TITLE
Intro to the DOM and Selenium documentation

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#27]

**Comment by Volatar** [comment]
Completed in 233b8ac6c2b256b27de0f30bf92e95f44bf620c7

**Comment by Volatar** [comment]
@dlingle1 assigned to review

**Comment by dlingle1** [comment]
Selenium documentation looks good to me.  I made one minor change, but other than that, I don't see anything that needs improvement.  Great work.
