### ISSUE TITLE
Test Case TC05 - Cart Functionality – Finish and Pay - Method Not Allowed Error

### ISSUE THREAD

**Issue by jslee5** [Volatar/Group7-repo-projects#35]
Bug Report
Summary: Test Case TC05 - Cart Functionality – Finish and Pay - Method Not Allowed Error
Date: [10-21-23]
Reporter: Jason Lee
Description:
While executing Test Case TC05 - Cart Functionality – Finish and Pay, the test did not pass as expected. The test case involves checking the functionality to finish and pay for items in the cart. Instead of the expected behavior, a "Method Not Allowed Error" occurred during the testing phase.
Test Case Details:
Test Case ID: TC05
Test Case Description: Cart Functionality – Finish and Pay
Test Data: Z: Zoolando, B: Back to the Present
Expected Results: Items should be displayed with payment total.
Actual Results: Method Not Allowed Error – Payment page was incomplete during testing phase.
Pass/Fail: Fail
Steps to Reproduce:
Go to the site.
Click on the Search button.
Input letter in the search box.
Click Search.
Click Add to Cart.
Repeat Steps 3-5.
Click Cart.
Click Finish and pay.
Additional Information:
Browser: Edge
Operating System: Windows 11
Screenshot:             
![image](https://github.com/Volatar/Group7-repo-projects/assets/89305357/1bf048ef-b7cd-4f03-b8db-295fdb4f917e)

           
Impact:
This bug affects the ability of users to complete their purchase through the cart functionality, which is a critical part of the system. It prevents users from successfully making a payment for items in their cart.

**Comment by audinpex** [comment]
Payment page accessible as of 9b152746d4dd8f64239b986d218fb37a6cf929ed - not all functionality completed, but page is accessible without error
