### ISSUE TITLE
Test Case TC07 - Error Handling – Add to Cart - Incorrect Item Found in Cart

### ISSUE THREAD

**Issue by jslee5** [Volatar/Group7-repo-projects#36]
Bug Report
Test Case TC07 - Error Handling – Add to Cart - Incorrect Item Found in Cart
Date: [10-21-23]
Reporter: Jason Lee
Description:
While executing Test Case TC07 - Error Handling – Add to Cart, the test did not pass as expected. The test case involves checking the error handling when attempting to add an item to the cart. Instead of the expected behavior (that the cart should be empty), an item with the name "N$" was found in the cart, which is incorrect.
Test Case Details:
Test Case ID: TC07
Test Case Description: Error Handling – Add to Cart
Test Data: N$
Expected Results: Cart should be empty.
Actual Results: Item found in cart with the name "N$"
Pass/Fail: Fail
Steps to Reproduce:
Go to the site.
Click on the Search button.
Input a letter in the search box.
Click Search.
Click Add to Cart.
Additional Information:
Browser: Edge
Operating System: Windows 11
Screenshot:  
                      
![image](https://github.com/Volatar/Group7-repo-projects/assets/89305357/a32a3b28-92cd-4b97-b388-09861f2eb4b8)
            
Impact:
This bug affects the functionality of adding items to the cart, as it allows an item with incorrect naming ("N$") to be added to the cart. It also results in inaccurate cart contents, which can lead to user confusion and potential issues during the checkout process.
Steps to Reproduce:
Navigate to the site.
Click on the Search button.
Input incorrect letter in the search box.
Click Search.
Click Add to Cart.
Expected Results:
The cart should be empty.
Actual Results:
An item with the name "N$" was found in the cart.
Pass/Fail: Fail
Comments:
The error handling for adding items to the cart is not working as expected. Instead of keeping the cart empty when trying to add an item, it allows an item with the name "N$" to be added. This does not align with the expected behavior, and it can potentially lead to confusion for users.

**Comment by audinpex** [comment]
Fix in 2f1b216275f6f477b416aaf34b983a0265c2341e - add to cart button no longer appears without valid movie found.
