### ISSUE TITLE
Application crashes when clicking add to cart button.

### ISSUE THREAD

**Issue by eceniza** [Volatar/Group7-repo-projects#37]
The application crashes when clicking the add to cart button.
Description
The application crashes when clicking the button add to cart on search.html when no movies are selected on the cart.

Steps to Reproduce
Open the application.
Click on “Search” under the web app title.
Click on “Add to Cart”.

Crashes.
Expected Results
 The system should display an error message on the screen, clearly indicating that the user attempted to click add to the cart without selecting a movie.
Actual Results
The application crashes and doesn’t display an error message.
![internal error](https://github.com/Volatar/Group7-repo-projects/assets/81448627/f9ff3c70-6a07-452d-b25d-d37fd340732b)

**Comment by audinpex** [comment]
Attempted fix in d2bda37386fcdf73fcfd1490740fff402b711a7e
