### ISSUE TITLE
BDD tutorial writing

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#39]

**Comment by Volatar** [comment]
Create based on https://youtube.com/playlist?list=PLUDwpEzHYYLsARXz1o3Ldt1FnvRbvlxsS&si=YhHtLh4NS8iprCJn

**Comment by jslee5** [comment]
Introduction to BBD tutorial part 1 documentation posted.

**Comment by jslee5** [comment]
Part 3 posted

**Comment by jslee5** [comment]
Part 5 submitted

**Comment by jslee5** [comment]
Part 7 submitted
