### ISSUE TITLE
Search page shows broken image before anything is searched

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#41]

**Comment by Volatar** [comment]
This is only relevant once the image-handling branch is merged

**Comment by Volatar** [comment]
![Image](https://github.com/Volatar/Group7-repo-projects/assets/1719182/d9e659f2-cd0a-44d9-a194-c2d8426e83fa)

**Comment by audinpex** [comment]
Accidentally fixed in 2f1b216275f6f477b416aaf34b983a0265c2341e when reorganizing movies.py and search html pages
