### ISSUE TITLE
Research for API lab

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#42]

**Comment by wcejahuerta** [comment]
[https://www.youtube.com/watch?v=ZHR4jlZyfOU&list=PLJlrbbAG08uP9-vr3pA1OQU6ZN8DVlINg](url)

**Comment by navyabd** [comment]
[https://youtu.be/5ZMpbdK0uqU?si=IE9iNGhFnrYiQBkI]

[https://youtu.be/zsYIw6RXjfM?si=VfuI7VuJm32Jhb9H](url)

[https://youtu.be/qbLc5a9jdXo?si=F3R080A5C7-dyLN5](url)
