### ISSUE TITLE
API Lab tutorial writing

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#49]

**Comment by dlingle1** [comment]
5d94f805a11c2106f3640a8c15d5014b2b52126a Created the API lab tutorial for using Postman.  Needs some finishing touches, but I will work on that tomorrow before our meeting.

**Comment by dlingle1** [comment]
159124ae12318ab37f2239ca8a2c52bfaf0ec7f4 Added pictures and fixed some grammar for the Postman tutorial.
