### ISSUE TITLE
TDD lab research

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#54]

**Comment by eceniza** [comment]
https://www.youtube.com/watch?v=NAjCDS-qxrQ&list=PLVWk3kKbCAAuPPr_eh4KNKdL2hDSNFH3H&index=1

**Comment by Volatar** [comment]
That one is too long.

This one should be better [https://www.youtube.com/watch?v=eAPmXQ0dC7Q](https://www.youtube.com/watch?v=eAPmXQ0dC7Q)
