### ISSUE TITLE
Playwright lab research

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#56]

**Comment by wcejahuerta** [comment]
https://youtube.com/playlist?list=PLhW3qG5bs-L9sJKoT1LC5grGT77sfW0Z8&si=XGfVgjRcq7gA7_KY

**Comment by navyabd** [comment]
[https://youtu.be/wGr5rz8WGCE?si=DJjocb2WZHLZlWMK](url)

**Comment by Volatar** [comment]
Wendy that one is very long, Something about half that length is probably better. But we could use it if we can't find anything else.

Navya one video is insufficient for our needs.

**Comment by navyabd** [comment]
[https://youtube.com/playlist?list=PL6flErFppaj0iQG2_Dd72Jz0bfrzZwMZH&si=A59tkBa60WgbxBPC](url)

**Comment by Volatar** [comment]
This is also probably too long hmm...

**Comment by navyabd** [comment]
[https://youtu.be/CK6MWehq7vI?si=etWsDble7UQMbcdh](url)

**Comment by Volatar** [comment]
This is a single video not a playlist.

**Comment by navyabd** [comment]
Yup, but the playlist I found  are long. I did not find a playlist that is half a dozen with 15-20 minute videos.

**Comment by Volatar** [comment]
Navya, it took me 15 seconds to find one.

And Wendy hasn't provided anything since her first link. Her link was the first thing on youtube when you search "playwright"

I feel like neither of you really looked at all.

**Comment by wcejahuerta** [comment]
All the videos I found were really long which is why I only provided the first link, I didn’t see a point in providing long videos we couldn’t use.

**Comment by Volatar** [comment]
So instead of saying that, you stayed silent?

**Comment by Volatar** [comment]
The tutorial we will be using is: [https://www.youtube.com/playlist?list=PLYDwWPRvXB8_W56h2C1z5zrlnAlvqpJ6A](https://www.youtube.com/playlist?list=PLYDwWPRvXB8_W56h2C1z5zrlnAlvqpJ6A)

**Comment by navyabd** [comment]
Hi Taylor! I did search a lot of videos, I took more time than 15 seconds,  I came across the video you shared right now too, but I did not like his content, it was not very clear or easy to understand, I didn't think it was worth sharing.

**Comment by wcejahuerta** [comment]
I apologize for staying silent but I was hoping I could find a tutorial the met the criteria before the meeting which is why I hadn’t said anything yet.
